---
jobs:
  build-and-push:
    executor: docker/docker
    parameters:
      base-image:
        type: string
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: tomonorimatsumura/ansible-test
          path: << parameters.base-image >>
          tag: << parameters.base-image >>-latest
      - docker/push:
          image: tomonorimatsumura/ansible-test
          tag: << parameters.base-image >>-latest

orbs:
  docker: circleci/docker@1.2.1

version: 2.1
workflows:
  version: 2
  build:
    triggers:
      - schedule:
          cron: "0 12 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-push:
          matrix:
            parameters:
              base-image: ['centos7', 'centos8']
