---
name: docker build
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: [centos7, centos7jp, centos8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Register docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tomonorimatsumura/ansible-test
          dockerfile: ${{ matrix.base-image }}/Dockerfile
          tags: ${{ matrix.base-image }}-latest
